### ISSUE TITLE
chart.destroy throws Uncaught TypeError: Cannot read property 'gauge_min' of null

### ISSUE THREAD

**Issue by Victori0us** [masayuki0812/c3#1205]
after redirect to another page and destroy view (when destroy view it is invoking and chart destroy) raise error: Uncaught TypeError: Cannot read property 'gauge_min' of null

**Comment by benharden** [comment]
I'm having the same issue. Looking at the call stack, the top function is d3_timer_step, so I think the problem must be occurring when the chart is destroyed whilst a transition is still running.

**Comment by grassick** [comment]
It also seems to permanently disable chart creation from working thereafter! Seems to happen with pie charts for me. At least I can't make a pie chart that has visible segments after it happens.

**Comment by aendrew** [comment]
Seems at least three people have encountered this, meaning it's a pretty well-confirmed bug at this point.

**Comment by diesburgm** [comment]
If it helps here is the full stack trace. If you destroy a chart while it is rendering the destroy sets all of the members to null, which then get accessed in the attrTween code being called on a timer from d3 to do the rendering.

Uncaught TypeError: Cannot read property 'gauge_min' of null
	c3_chart_internal_fn.updateAngle
	(anonymous function)
	attrTween
	(anonymous function)
	d3_class.forEach
	start
	(anonymous function)
	d3_timer_mark
	d3_timer_step

**Comment by louy** [comment]
+1 @masayuki0812

**Comment by aendrew** [comment]
#1205 has been merged, so am finally closing this issue! :D Many thinks to @diesburgm for the PR!

**Comment by joshthecoder** [comment]
I seem to be running into this issue again but the stack trace is different.

<img width="634" alt="screen shot 2016-05-02 at 2 09 30 pm" src="https://cloud.githubusercontent.com/assets/25644/14968044/9a09f072-106f-11e6-804c-ae905beb8d1e.png">

Seems to happen on destroy while transitioning between views. The chart in the view
being presented next never loads.

**Comment by aendrew** [comment]
@joshthecoder Mind providing which version of C3 you're using? If 0.4.11 (latest), could you please create a new issue and reference this one in it? Thanks!

**Comment by sushantdhiman** [comment]
I am facing this same issue

```js
c3.js?84d1:2148 Uncaught TypeError: Cannot read property 'keys' of null
    at ChartInternal.c3_chart_internal_fn.convertDataToTargets (eval at <anonymous> (http://localhost:3000/build/bundle.js:7791:2), <anonymous>:2148:24)
    at ChartInternal.c3_chart_internal_fn.loadFromArgs (eval at <anonymous> (http://localhost:3000/build/bundle.js:7791:2), <anonymous>:2309:24)
    at SVGGElement.eval (eval at <anonymous> (http://localhost:3000/build/bundle.js:7791:2), <anonymous>:6321:20)
    at SVGGElement.eval (eval at <anonymous> (http://localhost:3000/build/bundle.js:7791:2), <anonymous>:1007:38)
    at SVGGElement.event (eval at <anonymous> (http://localhost:3000/build/bundle.js:7785:2), <anonymous>:504:42)
    at tick (eval at <anonymous> (http://localhost:3000/build/bundle.js:7785:2), <anonymous>:8959:50)
    at Object.eval [as c] (eval at <anonymous> (http://localhost:3000/build/bundle.js:7785:2), <anonymous>:8936:24)
    at d3_timer_mark (eval at <anonymous> (http://localhost:3000/build/bundle.js:7785:2), <anonymous>:2166:35)
    at d3_timer_step (eval at <anonymous> (http://localhost:3000/build/bundle.js:7785:2), <anonymous>:2147:15)c3_chart_internal_fn.convertDataToTargets @ c3.js?84d1:2148c3_chart_internal_fn.loadFromArgs @ c3.js?84d1:2309(anonymous function) @ c3.js?84d1:6321(anonymous function) @ c3.js?84d1:1007event @ d3.js?8d8f:504tick @ d3.js?8d8f:8959(anonymous function) @ d3.js?8d8f:8936d3_timer_mark @ d3.js?8d8f:2166d3_timer_step @ d3.js?8d8f:2147
```

version: `0.4.11`

It goes away if i dont use `unload` option in `load`, may be related to `destroy` call

**Comment by pajcho** [comment]
@joshthecoder @sushantdhiman You can take a look at my pull request that fixes this issue https://github.com/c3js/c3/pull/1949

**Comment by sushantdhiman** [comment]
Thanks for this fix @pajcho , Internally our team have decided to use D3 directly instead :)

**Comment by ilacyero** [comment]
Same issue it is happening in version `0.4.11`
```
modules.js?hash=cb4e0f1…:117357 Uncaught TypeError: Cannot read property 'keys' of null(…)
   c3_chart_internal_fn.convertDataToTargets @ modules.js?hash=cb4e0f1…:117357
   c3_chart_internal_fn.loadFromArgs @ modules.js?hash=cb4e0f1…:117518
   (anonymous function) @ modules.js?hash=cb4e0f1…:121530
   (anonymous function) @ modules.js?hash=cb4e0f1…:116216
   event @ modules.js?hash=cb4e0f1…:123940
   tick @ modules.js?hash=cb4e0f1…:132395d3
   _timer_mark @ modules.js?hash=cb4e0f1…:125602d3
   _timer_step @ modules.js?hash=cb4e0f1…:125583
```

**Comment by kakato10** [comment]
I ran into the same issue, on 0.4.11. Anything new about the PR that solves it?

`Uncaught TypeError: Cannot read property 'keys' of null
    at ChartInternal.c3_chart_internal_fn.convertDataToTargets (vendor.9d1c45.js:88053)
    at ChartInternal.c3_chart_internal_fn.loadFromArgs (vendor.9d1c45.js:88214)
    at vendor.9d1c45.js:92226
    at ChartInternal.c3_chart_internal_fn.unload (vendor.9d1c45.js:88229)
    at Chart.c3_chart_fn.load (vendor.9d1c45.js:92225)
    at invokeFunc (vendor.9d1c45.js:32997)
    at trailingEdge (vendor.9d1c45.js:33044)
    at timerExpired (vendor.9d1c45.js:33032)`

**Comment by mervinva** [comment]
Same issue on 0.4.18 
TypeError: Cannot read property 'keys' of null
    at i.C.convertDataToTargets (c3.min.js:1)
    at i.C.loadFromArgs (c3.min.js:1)
    at e.P.load (c3.min.js:1)
