### ISSUE TITLE
Creation Error : a.axisTimeFormat.multi is not a function

### ISSUE THREAD

**Issue by ElaineYu** [masayuki0812/c3#1539]
Hi, I'm trying to get the most basic C3 JS example up and running in my Angular application (1.4.7)

I've followed these C3 Get Started Instructions and downloaded the most recent files from  the latest (0.4.10) release:
http://c3js.org/gettingstarted.html

Added respective paths:

`<link href="/lib/c3/c3.css" rel="stylesheet" type="text/css">`
`<script src="/lib/d3/d3.v3.min.js"></script>`
`<script src="/lib/c3/c3.min.js"></script>`

And tried to add this basic code to my view just to have a look:

    <div id="chart"></div>
    <script type="text/javascript">
      var chart = c3.generate({
          bindto: '#chart',
          data: {
            columns: [
              ['data1', 30, 200, 100, 400, 150, 250],
              ['data2', 50, 20, 10, 40, 15, 25]
            ]
          }
      });
    </script>

But it returns this error and renders nothing:

<pre><code>
TypeError: a.axisTimeFormat.multi is not a function
    at e.i.initParams (http://localhost:3000/lib/c3/c3.min.js:1:6498)
    at e.i.init (http://localhost:3000/lib/c3/c3.min.js:1:5306)
    at new d (http://localhost:3000/lib/c3/c3.min.js:1:291)
    at Object.k.generate (http://localhost:3000/lib/c3/c3.min.js:1:5116)
    at eval (eval at <anonymous> (http://localhost:3000/js/jquery/dist/jquery.min.js:2:2538), <anonymous>:1:16)
    at eval (native)
    at Function.n.extend.globalEval (http://localhost:3000/js/jquery/dist/jquery.min.js:2:2538)
    at n.fn.extend.domManip (http://localhost:3000/js/jquery/dist/jquery.min.js:3:17225)
    at n.fn.extend.append (http://localhost:3000/js/jquery/dist/jquery.min.js:3:14908)
    at null.<anonymous> (http://localhost:3000/js/jquery/dist/jquery.min.js:3:16268) <div class="ng-view ng-scope">
</pre></code>

I've tried to install this using this library for angular:
https://github.com/jettro/c3-angular-directive
But have gotten the same error.

Any help would be greatly appreciated!  Thanks!

**Comment by ElaineYu** [comment]
Ah, sorry, I think this probably more of an Angular issue than a C3 issue.  Works fine on a simple index page but it doesn't load properly into partials.  Will take this to stackoverflow...
